# Generated by Django 5.1.2 on 2024-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(default='https://pin.it/6EYVqY3A4', max_length=500),
            preserve_default=False,
        ),
    ]
