# Generated by Django 5.1.2 on 2024-12-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_avatar_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(default='https://i.pinimg.com/736x/50/42/90/504290aa11c08e6aa19831be382c8de2.jpg', max_length=500),
        ),
    ]
