# Generated by Django 5.1.2 on 2024-10-25 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalChat', '0003_commentglobal_delete_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentGlobal',
            new_name='Comment',
        ),
    ]
