# Generated by Django 5.1.2 on 2024-10-25 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalChat', '0004_rename_commentglobal_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_forums', to=settings.AUTH_USER_MODEL),
        ),
    ]
