# Generated by Django 5.1.2 on 2024-10-23 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('user_choices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
