# Generated by Django 5.1.2 on 2024-10-24 03:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('user_choices', '0002_alter_userchoice_item_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchoice',
            old_name='item_id',
            new_name='selected_item',
        ),
        migrations.AlterUniqueTogether(
            name='userchoice',
            unique_together={('user', 'selected_item')},
        ),
    ]
