# Generated by Django 5.1.2 on 2024-10-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_choices', '0003_rename_item_id_userchoice_selected_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
