# Generated by Django 5.1.2 on 2024-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_choices', '0004_userchoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=-2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
