# Generated by Django 5.1.2 on 2024-10-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_choices', '0005_userchoice_created_at_userchoice_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='updated_at',
        ),
    ]
