# Generated by Django 5.1.1 on 2024-10-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
        ('products', '0003_comment'),
    ]

    operations = [
    ]
